name: Hello Sruthi Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello Sruthi! This is your first GitHub Action!"
